apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: los-config-service
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/jbaddam17/loanoriginx-ci-cd.git
    path: los-config-service
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-los-config-service

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true

    automated:
      selfHeal: true
      prune: true
      allowEmpty: false
